"""Engine to populate the 14 AMS Excel templates with session entity data.

Takes session entities (hierarchy nodes, criticality assessments, failure modes,
maintenance tasks, work packages, materials, SAP package) and writes them into
the standard AMS template xlsx format — matching the structure, styling, data
validations, instructions sheets, and reference sheets of the standard templates
generated by ``templates/generate_templates.py``.

Usage:
    from tools.engines.template_population_engine import TemplatePopulationEngine

    results = TemplatePopulationEngine.populate_all(
        session_entities=session.entities,
        sap_package=session.sap_upload_package,
        output_dir="output/session_xyz",
        plant_code="OCP-JFC",
    )
    # results = {"01_equipment_hierarchy.xlsx": Path(...), ...}
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from tools.engines._template_constants import (
    ABC_CLASSES,
    BUDGETED_AS_VALUES,
    BUDGETED_LIFE_UNITS,
    CAUSES,
    CRIT_METHODS,
    CRITICALITIES,
    EQUIP_STATUSES,
    FAILURE_CONSEQUENCES,
    FAILURE_PATTERNS,
    FAILURE_TYPES,
    FM_COMBOS,
    FREQUENCY_UNITS,
    FUNCTION_TYPES,
    FSN_CLASSES,
    INSTR_01_HIERARCHY,
    INSTR_02_CRITICALITY,
    INSTR_03_FAILURE_MODES,
    INSTR_04_TASKS,
    INSTR_05_WORK_PACKAGES,
    INSTR_07_SPARE_PARTS,
    INSTR_14_STRATEGY,
    JUSTIFICATION_CATEGORIES,
    LABOUR_SPECIALTIES,
    MECHANISMS,
    STRATEGY_RULES,
    STRATEGY_STATUSES,
    STRATEGY_TYPES,
    TASK_CONSTRAINTS,
    TASK_TYPES,
    UNITS_OF_MEASURE,
    VED_CLASSES,
    WP_CONSTRAINTS,
    WP_TYPES,
)

logger = logging.getLogger(__name__)

# OCP brand colors matching existing templates
_OCP_GREEN = "1B5E20"
_HEADER_FONT_COLOR = "FFFFFF"

# Number of data rows to apply validation to
_VALIDATION_ROWS = 500


def _get_openpyxl():
    """Lazy import openpyxl."""
    try:
        import openpyxl
        from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
        return openpyxl, Font, PatternFill, Alignment, Border, Side
    except ImportError as exc:
        raise ImportError(
            "openpyxl is required for template population. "
            "Install it with: pip install openpyxl"
        ) from exc


def _get_dv():
    """Lazy import DataValidation and get_column_letter."""
    from openpyxl.utils import get_column_letter
    from openpyxl.worksheet.datavalidation import DataValidation
    return DataValidation, get_column_letter


class TemplatePopulationEngine:
    """Populates AMS template xlsx files from session entities."""

    # ── Style objects (created lazily) ───────────────────────────
    _styles_cache: dict[str, Any] | None = None

    @classmethod
    def _styles(cls):
        """Get style objects, creating them lazily."""
        if cls._styles_cache is None:
            _, Font, PatternFill, Alignment, Border, Side = _get_openpyxl()
            cls._styles_cache = {
                "header_font": Font(name="Calibri", size=11, bold=True, color=_HEADER_FONT_COLOR),
                "header_fill": PatternFill(start_color=_OCP_GREEN, end_color=_OCP_GREEN, fill_type="solid"),
                "header_align": Alignment(horizontal="center", vertical="center", wrap_text=True),
                "data_font": Font(name="Calibri", size=10),
                "instr_header_font": Font(name="Calibri", size=11, bold=True, color=_OCP_GREEN),
                "thin_border": Border(
                    left=Side(style="thin"), right=Side(style="thin"),
                    top=Side(style="thin"), bottom=Side(style="thin"),
                ),
                "wrap_align": Alignment(wrap_text=True, vertical="top"),
            }
        return cls._styles_cache

    # ── Core helpers ─────────────────────────────────────────────

    @staticmethod
    def _create_workbook(title: str = "AMS Export"):
        openpyxl, *_ = _get_openpyxl()
        wb = openpyxl.Workbook()
        wb.properties.creator = "VSC AMS"
        wb.properties.description = f"AMS Export — {title}"
        wb.properties.last_modified_by = "VSC AMS"
        return wb

    @classmethod
    def _style_header(cls, ws, headers: list[str]) -> None:
        s = cls._styles()
        ws.append(headers)
        for cell in ws[1]:
            cell.font = s["header_font"]
            cell.fill = s["header_fill"]
            cell.alignment = s["header_align"]
            cell.border = s["thin_border"]
        ws.freeze_panes = "A2"

    @classmethod
    def _write_data_row(cls, ws, row_data: list, row_idx: int) -> None:
        """Write a single data row with DATA_FONT + THIN_BORDER + WRAP_ALIGN."""
        s = cls._styles()
        for col_idx, value in enumerate(row_data, start=1):
            cell = ws.cell(row=row_idx, column=col_idx, value=value)
            cell.font = s["data_font"]
            cell.border = s["thin_border"]
            cell.alignment = s["wrap_align"]

    @classmethod
    def _append_data_row(cls, ws, row_data: list) -> None:
        """Append a styled data row after the last row."""
        row_idx = ws.max_row + 1
        cls._write_data_row(ws, row_data, row_idx)

    @staticmethod
    def _auto_size(ws) -> None:
        """Auto-size columns based on header length (matching standard templates)."""
        _, _, _, _, _, _ = _get_openpyxl()
        from openpyxl.utils import get_column_letter
        for col_idx in range(1, ws.max_column + 1):
            header_val = ws.cell(row=1, column=col_idx).value or ""
            width = min(max(len(str(header_val)) + 4, 12), 40)
            ws.column_dimensions[get_column_letter(col_idx)].width = width

    @classmethod
    def _add_data_validation(cls, ws, col_idx: int, values: list, num_rows: int = _VALIDATION_ROWS) -> None:
        """Add dropdown data validation to a column.

        If the inline formula exceeds 255 chars (Excel limit), automatically
        creates a hidden 'Lookups' sheet and uses a cell-range reference.
        """
        DataValidation, get_column_letter = _get_dv()

        inline_formula = ",".join(values)
        if len(inline_formula) + 2 <= 255:
            formula = '"' + inline_formula + '"'
        else:
            wb = ws.parent
            if "Lookups" not in wb.sheetnames:
                lk = wb.create_sheet("Lookups")
                lk.sheet_state = "hidden"
                lk._lookup_next_col = 1
            else:
                lk = wb["Lookups"]
            lk_col = getattr(lk, "_lookup_next_col", 1)
            for i, val in enumerate(values, start=1):
                lk.cell(row=i, column=lk_col, value=val)
            lk_letter = get_column_letter(lk_col)
            formula = f"=Lookups!${lk_letter}$1:${lk_letter}${len(values)}"
            lk._lookup_next_col = lk_col + 1

        dv = DataValidation(type="list", formula1=formula, allow_blank=True)
        dv.error = "Please select a valid value from the dropdown."
        dv.errorTitle = "Invalid Value"
        col_letter = get_column_letter(col_idx)
        dv.add(f"{col_letter}2:{col_letter}{num_rows}")
        ws.add_data_validation(dv)

    @classmethod
    def _add_instructions_sheet(cls, wb, field_descriptions: list[tuple]) -> None:
        """Add an Instructions sheet with field descriptions (identical to standard)."""
        s = cls._styles()
        ws = wb.create_sheet("Instructions")
        headers = ["Field Name", "Data Type", "Required", "Valid Values / Constraints", "Description"]
        for col_idx, h in enumerate(headers, start=1):
            cell = ws.cell(row=1, column=col_idx, value=h)
            cell.fill = s["header_fill"]
            cell.font = s["header_font"]
            cell.border = s["thin_border"]
        ws.freeze_panes = "A2"

        for row_idx, (name, dtype, required, valid_values, desc) in enumerate(field_descriptions, start=2):
            ws.cell(row=row_idx, column=1, value=name).font = s["instr_header_font"]
            ws.cell(row=row_idx, column=2, value=dtype).font = s["data_font"]
            ws.cell(row=row_idx, column=3, value=required).font = s["data_font"]
            ws.cell(row=row_idx, column=4, value=valid_values).font = s["data_font"]
            ws.cell(row=row_idx, column=5, value=desc).font = s["data_font"]
            for c in range(1, 6):
                ws.cell(row=row_idx, column=c).border = s["thin_border"]
                ws.cell(row=row_idx, column=c).alignment = s["wrap_align"]

        ws.column_dimensions["A"].width = 25
        ws.column_dimensions["B"].width = 15
        ws.column_dimensions["C"].width = 10
        ws.column_dimensions["D"].width = 40
        ws.column_dimensions["E"].width = 50

    @classmethod
    def _add_fm_combos_sheet(cls, wb) -> None:
        """Add 'Valid FM Combinations' reference sheet."""
        s = cls._styles()
        ws_combo = wb.create_sheet("Valid FM Combinations")
        ws_combo.cell(row=1, column=1, value="Mechanism").fill = s["header_fill"]
        ws_combo.cell(row=1, column=1).font = s["header_font"]
        ws_combo.cell(row=1, column=2, value="Cause").fill = s["header_fill"]
        ws_combo.cell(row=1, column=2).font = s["header_font"]
        ws_combo.freeze_panes = "A2"

        for row_idx, (mech, cause) in enumerate(FM_COMBOS, start=2):
            ws_combo.cell(row=row_idx, column=1, value=mech).font = s["data_font"]
            ws_combo.cell(row=row_idx, column=2, value=cause).font = s["data_font"]
        ws_combo.column_dimensions["A"].width = 30
        ws_combo.column_dimensions["B"].width = 35

    @classmethod
    def _add_strategy_rules_sheet(cls, wb) -> None:
        """Add 'Strategy Type Rules' reference sheet."""
        _, _, _, _, _, _ = _get_openpyxl()
        from openpyxl.utils import get_column_letter
        s = cls._styles()
        ws_rules = wb.create_sheet("Strategy Type Rules")
        rule_headers = ["Tactics Type", "Has Primary Task?", "Has Secondary Task?",
                        "Has Acceptable Limits?", "Has Interval?", "Description"]
        for col_idx, h in enumerate(rule_headers, start=1):
            cell = ws_rules.cell(row=1, column=col_idx, value=h)
            cell.fill = s["header_fill"]
            cell.font = s["header_font"]
        ws_rules.freeze_panes = "A2"
        for row_idx, row_data in enumerate(STRATEGY_RULES, start=2):
            for col_idx, val in enumerate(row_data, start=1):
                cell = ws_rules.cell(row=row_idx, column=col_idx, value=val)
                cell.font = s["data_font"]
                cell.alignment = s["wrap_align"]
        for col_idx in range(1, 7):
            ws_rules.column_dimensions[get_column_letter(col_idx)].width = 25

    @staticmethod
    def _save(wb, output_path: Path) -> Path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        wb.save(output_path)
        logger.info("Template written: %s", output_path)
        return output_path

    @classmethod
    def _safe_get(cls, entity: dict, key: str, default: Any = "") -> Any:
        """Safely get a value from an entity dict."""
        val = entity.get(key, default)
        return val if val is not None else default

    # ══════════════════════════════════════════════════════════════════
    # T-01: Equipment Hierarchy
    # ══════════════════════════════════════════════════════════════════

    # Level strings produced by agents (e.g. "L1_SITE") → int
    _LEVEL_MAP = {
        "L1_SITE": 1, "L1_PLANT": 1,
        "L2_AREA": 2, "L2_PLANT": 2,
        "L3_SYSTEM": 3, "L3_AREA": 3,
        "L4_EQUIPMENT": 4,
        "L5_SUBASSEMBLY": 5, "L5_SUBUNIT": 5,
        "L6_COMPONENT": 6, "L6_MAINTAINABLE_ITEM": 6,
    }

    # ISO 14224 level name mapping
    _ISO_LEVEL_NAMES = {
        1: ("Industry", 5),
        2: ("Business Category", 6),
        3: ("Installation", 7),
        4: ("Plant / Unit", 8),
        5: ("Equipment Class / Unit", 9),
        6: ("Subunit", None),
        7: ("Maintainable Item", None),
    }

    @classmethod
    def _coerce_level(cls, raw) -> int:
        """Coerce level value (int or string like 'L1_SITE') to int."""
        if isinstance(raw, int):
            return raw
        if isinstance(raw, str):
            if raw.upper() in cls._LEVEL_MAP:
                return cls._LEVEL_MAP[raw.upper()]
            for ch in raw:
                if ch.isdigit():
                    return int(ch)
        try:
            return int(raw)
        except (TypeError, ValueError):
            return 0

    @staticmethod
    def _get_meta(node: dict) -> dict:
        """Get metadata dict from node, checking both 'metadata' and 'metadata_json' keys."""
        return node.get("metadata", node.get("metadata_json", {})) or {}

    @classmethod
    def populate_01_hierarchy(
        cls, nodes: list[dict], output_path: Path,
    ) -> Path:
        """Write hierarchy nodes to 01_equipment_hierarchy.xlsx.

        Sheet 1 — Equipment Hierarchy: one row per equipment (L4+), with
        flattened plant/area/system ancestors. Standard 18-column structure.
        Sheet 2 — Equipment BOM: full tree of all nodes per equipment.
        """
        wb = cls._create_workbook("Equipment Hierarchy")

        # ── Shared helpers ────────────────────────────────────────
        by_id: dict[str, dict] = {n.get("node_id", ""): n for n in nodes}

        def _ancestor(node: dict, target_level: int) -> dict:
            current = node
            visited = set()
            while current:
                nid = current.get("node_id", "")
                if nid in visited:
                    break
                visited.add(nid)
                if cls._coerce_level(current.get("level")) == target_level:
                    return current
                parent_id = current.get("parent_node_id")
                current = by_id.get(parent_id, {}) if parent_id else {}
            return {}

        def _node_tag(node: dict) -> str:
            return node.get("tag") or node.get("code") or node.get("node_id", "")

        # ── Sheet 1: Equipment Hierarchy (L4+ only) — standard 18 columns ──
        ws = wb.active
        ws.title = "Equipment Hierarchy"

        headers = [
            "plant_id", "plant_name", "area_code", "area_name",
            "system_code", "system_name", "equipment_tag",
            "equipment_description", "equipment_type", "manufacturer",
            "model", "serial_number", "power_kw", "weight_kg",
            "criticality", "status", "sap_func_loc", "installation_date",
        ]
        cls._style_header(ws, headers)

        equipment_nodes = [
            n for n in nodes if cls._coerce_level(n.get("level", 0)) >= 4
        ]

        for row_num, node in enumerate(equipment_nodes, start=2):
            plant = _ancestor(node, 1)
            area = _ancestor(node, 2)
            system = _ancestor(node, 3)
            meta = cls._get_meta(node)

            cls._write_data_row(ws, [
                _node_tag(plant) if plant else "",
                cls._safe_get(plant, "name"),
                _node_tag(area) if area else "",
                cls._safe_get(area, "name"),
                _node_tag(system) if system else "",
                cls._safe_get(system, "name"),
                _node_tag(node),
                cls._safe_get(node, "name"),
                cls._safe_get(node, "equipment_type",
                              cls._safe_get(meta, "equipment_type",
                                            cls._safe_get(node, "node_type"))),
                cls._safe_get(node, "manufacturer",
                              cls._safe_get(meta, "manufacturer")),
                cls._safe_get(node, "model",
                              cls._safe_get(meta, "model")),
                cls._safe_get(node, "serial_number",
                              cls._safe_get(meta, "serial_number")),
                cls._safe_get(node, "power_kw",
                              cls._safe_get(meta, "power_kw")),
                cls._safe_get(node, "weight_kg",
                              cls._safe_get(meta, "weight_kg")),
                cls._safe_get(node, "criticality"),
                cls._safe_get(node, "status", "ACTIVE"),
                cls._safe_get(node, "sap_func_loc"),
                cls._safe_get(node, "installation_date"),
            ], row_num)

        # Data validations
        cls._add_data_validation(ws, 15, CRITICALITIES)
        cls._add_data_validation(ws, 16, EQUIP_STATUSES)

        cls._auto_size(ws)

        # ── Sheet 2: Equipment BOM (full tree per L4 equipment) ──
        ws_bom = wb.create_sheet("Equipment BOM")
        bom_headers = [
            "equipment_tag", "level", "node_type", "code", "name",
            "name_fr", "parent_code", "order", "mi_category",
            "manufacturer", "iso14224_level", "iso14224_level_name",
        ]
        cls._style_header(ws_bom, bom_headers)

        def _find_equipment_root(node: dict) -> dict:
            current = node
            visited = set()
            while current:
                nid = current.get("node_id", "")
                if nid in visited:
                    break
                visited.add(nid)
                if cls._coerce_level(current.get("level")) == 4:
                    return current
                parent_id = current.get("parent_node_id")
                current = by_id.get(parent_id, {}) if parent_id else {}
            return {}

        sorted_nodes = sorted(
            nodes,
            key=lambda n: (cls._coerce_level(n.get("level", 0)), n.get("node_id", "")),
        )

        order_counter: dict[str, int] = {}
        bom_row = 2
        for node in sorted_nodes:
            level = cls._coerce_level(node.get("level", 0))
            if level < 4:
                continue

            equip_root = _find_equipment_root(node)
            equip_tag = _node_tag(equip_root) if equip_root else _node_tag(node)

            parent_id = node.get("parent_node_id", "")
            parent_node = by_id.get(parent_id, {})
            parent_code = _node_tag(parent_node) if parent_node and cls._coerce_level(
                parent_node.get("level", 0)) >= 4 else None

            parent_key = parent_id or "__root__"
            order_counter.setdefault(parent_key, 0)
            order_counter[parent_key] += 1

            iso_level = level + 1
            iso_name = cls._ISO_LEVEL_NAMES.get(iso_level, ("", None))[0]

            bom_meta = cls._get_meta(node)
            cls._write_data_row(ws_bom, [
                equip_tag,
                level,
                cls._safe_get(node, "node_type",
                              cls._safe_get(node, "equipment_type")),
                _node_tag(node),
                cls._safe_get(node, "name"),
                cls._safe_get(node, "name_fr"),
                parent_code,
                order_counter[parent_key] - 1,
                cls._safe_get(node, "mi_category"),
                cls._safe_get(node, "manufacturer",
                              cls._safe_get(bom_meta, "manufacturer")),
                iso_level,
                iso_name,
            ], bom_row)
            bom_row += 1

        cls._auto_size(ws_bom)

        # Instructions
        cls._add_instructions_sheet(wb, INSTR_01_HIERARCHY)

        return cls._save(wb, output_path)

    # ══════════════════════════════════════════════════════════════════
    # T-02: Criticality Assessment
    # ══════════════════════════════════════════════════════════════════

    CRIT_CATEGORIES = [
        "safety", "health", "environment", "production", "operating_cost",
        "capital_cost", "schedule", "revenue", "communications",
        "compliance", "reputation",
    ]

    @classmethod
    def populate_02_criticality(
        cls,
        assessments: list[dict],
        nodes: list[dict],
        output_path: Path,
    ) -> Path:
        """Write criticality assessments to 02_criticality_assessment.xlsx."""
        wb = cls._create_workbook("Criticality Assessment")
        ws = wb.active
        ws.title = "Criticality Assessment"

        headers = ["equipment_tag", "method"] + cls.CRIT_CATEGORIES + ["probability"]
        cls._style_header(ws, headers)

        by_id = {n.get("node_id", ""): n for n in nodes}

        for row_num, ca in enumerate(assessments, start=2):
            node = by_id.get(ca.get("node_id", ""), {})
            tag = node.get("tag", node.get("code", ca.get("node_id", "")))
            method = cls._safe_get(ca, "method", "FULL_MATRIX")

            score_map: dict[str, int | str] = {}
            for cs in ca.get("criteria_scores", []):
                cat_key = str(cs.get("category", "")).lower()
                val = cs.get("score", cs.get("consequence_level", ""))
                score_map[cat_key] = val

            consequences = ca.get("consequences", ca)
            cat_scores = []
            for cat in cls.CRIT_CATEGORIES:
                val = score_map.get(cat, "")
                if val == "":
                    val = cls._safe_get(consequences, cat, "")
                cat_scores.append(val)

            cls._write_data_row(ws, [
                tag, method,
                *cat_scores,
                cls._safe_get(ca, "probability", cls._safe_get(ca, "likelihood", "")),
            ], row_num)

        # Data validations
        cls._add_data_validation(ws, 2, CRIT_METHODS)
        for col_idx in range(3, 14):
            cls._add_data_validation(ws, col_idx, ["1", "2", "3", "4", "5"])

        cls._auto_size(ws)
        cls._add_instructions_sheet(wb, INSTR_02_CRITICALITY)
        return cls._save(wb, output_path)

    # ══════════════════════════════════════════════════════════════════
    # T-03: Failure Modes
    # ══════════════════════════════════════════════════════════════════

    @classmethod
    def populate_03_failure_modes(
        cls,
        failure_modes: list[dict],
        functions: list[dict],
        functional_failures: list[dict],
        nodes: list[dict],
        output_path: Path,
    ) -> Path:
        """Write failure modes to 03_failure_modes.xlsx."""
        wb = cls._create_workbook("Failure Modes")
        ws = wb.active
        ws.title = "Failure Modes"

        headers = [
            "equipment_tag", "function_description", "function_type",
            "failure_type", "what_component", "mechanism", "cause",
            "failure_pattern", "failure_consequence", "evidence",
            "downtime_hours", "detection_method",
            "rpn_severity", "rpn_occurrence", "rpn_detection",
        ]
        cls._style_header(ws, headers)

        by_id = {n.get("node_id", ""): n for n in nodes}
        func_by_id = {f.get("function_id", ""): f for f in functions}
        ff_by_id = {ff.get("failure_id", ""): ff for ff in functional_failures}

        for row_num, fm in enumerate(failure_modes, start=2):
            func_id = fm.get("function_id", "")
            failure_id = fm.get("failure_id", fm.get("functional_failure_id", ""))
            func = func_by_id.get(func_id, {})
            ff = ff_by_id.get(failure_id, {})
            node_id = func.get("node_id", fm.get("node_id", ""))
            node = by_id.get(node_id, {})
            tag = node.get("tag", node.get("code", node_id))

            fe = fm.get("failure_effect", {})
            if not isinstance(fe, dict):
                fe = {}

            cls._write_data_row(ws, [
                tag,
                cls._safe_get(func, "description"),
                cls._safe_get(func, "function_type"),
                cls._safe_get(ff, "failure_type", cls._safe_get(fm, "failure_type")),
                cls._safe_get(fm, "what_component",
                              cls._safe_get(fm, "what",
                              cls._safe_get(fm, "component"))),
                cls._safe_get(fm, "mechanism"),
                cls._safe_get(fm, "cause"),
                cls._safe_get(fm, "failure_pattern"),
                cls._safe_get(fm, "failure_consequence", cls._safe_get(fm, "consequence")),
                cls._safe_get(fm, "evidence",
                              cls._safe_get(fe, "evidence",
                              cls._safe_get(fm, "detection_evidence"))),
                cls._safe_get(fm, "downtime_hours",
                              cls._safe_get(fe, "estimated_downtime_hours")),
                cls._safe_get(fm, "detection_method",
                              cls._safe_get(fe, "detection_method")),
                cls._safe_get(fm, "rpn_severity", cls._safe_get(fm, "severity")),
                cls._safe_get(fm, "rpn_occurrence", cls._safe_get(fm, "occurrence")),
                cls._safe_get(fm, "rpn_detection", cls._safe_get(fm, "detection")),
            ], row_num)

        # Data validations
        cls._add_data_validation(ws, 3, FUNCTION_TYPES)
        cls._add_data_validation(ws, 4, FAILURE_TYPES)
        cls._add_data_validation(ws, 6, MECHANISMS)
        cls._add_data_validation(ws, 7, CAUSES)
        cls._add_data_validation(ws, 8, FAILURE_PATTERNS)
        cls._add_data_validation(ws, 9, FAILURE_CONSEQUENCES)

        cls._auto_size(ws)

        # Reference sheet + instructions
        cls._add_fm_combos_sheet(wb)
        cls._add_instructions_sheet(wb, INSTR_03_FAILURE_MODES)
        return cls._save(wb, output_path)

    # ══════════════════════════════════════════════════════════════════
    # T-04: Maintenance Tasks (4 sheets)
    # ══════════════════════════════════════════════════════════════════

    @classmethod
    def populate_04_tasks(
        cls,
        tasks: list[dict],
        materials: list[dict],
        output_path: Path,
    ) -> Path:
        """Write maintenance tasks to 04_maintenance_tasks.xlsx (4 sheets)."""
        wb = cls._create_workbook("Maintenance Tasks")

        # Sheet 1: Tasks
        ws_tasks = wb.active
        ws_tasks.title = "Tasks"
        cls._style_header(ws_tasks, [
            "task_id", "task_name", "task_name_fr", "task_type",
            "constraint", "access_time_hours",
            "budgeted_as", "budgeted_life", "budgeted_life_time_units",
            "budgeted_life_operational_units",
            "consequences", "justification", "origin", "notes",
        ])
        for row_num, t in enumerate(tasks, start=2):
            cls._write_data_row(ws_tasks, [
                cls._safe_get(t, "task_id"),
                cls._safe_get(t, "name",
                              cls._safe_get(t, "description",
                              cls._safe_get(t, "task_name"))),
                cls._safe_get(t, "name_fr",
                              cls._safe_get(t, "description_fr",
                              cls._safe_get(t, "task_name_fr"))),
                cls._safe_get(t, "task_type", cls._safe_get(t, "type")),
                cls._safe_get(t, "constraint"),
                cls._safe_get(t, "access_time_hours"),
                cls._safe_get(t, "budgeted_as"),
                cls._safe_get(t, "budgeted_life"),
                cls._safe_get(t, "budgeted_life_time_units"),
                cls._safe_get(t, "budgeted_life_operational_units"),
                cls._safe_get(t, "consequences", cls._safe_get(t, "failure_consequence")),
                cls._safe_get(t, "justification"),
                cls._safe_get(t, "origin", "AI_GENERATED"),
                cls._safe_get(t, "notes"),
            ], row_num)

        # Tasks sheet validations
        cls._add_data_validation(ws_tasks, 4, TASK_TYPES)
        cls._add_data_validation(ws_tasks, 5, TASK_CONSTRAINTS)
        cls._add_data_validation(ws_tasks, 7, BUDGETED_AS_VALUES)
        cls._add_data_validation(ws_tasks, 9, BUDGETED_LIFE_UNITS)
        cls._add_data_validation(ws_tasks, 10, FREQUENCY_UNITS)

        # Sheet 2: Task_Labour
        ws_labour = wb.create_sheet("Task_Labour")
        cls._style_header(ws_labour, [
            "labour_id", "task_id", "worker_id", "specialty",
            "quantity", "hours_per_person", "hourly_rate_usd", "company",
        ])
        labour_row = 2
        for t in tasks:
            labour = t.get("labour_resources", t.get("labour", t.get("crew", [])))
            if isinstance(labour, list):
                for i, lb in enumerate(labour):
                    cls._write_data_row(ws_labour, [
                        cls._safe_get(lb, "labour_id", f"{t.get('task_id', '')}-L{i+1}"),
                        cls._safe_get(t, "task_id"),
                        cls._safe_get(lb, "worker_id"),
                        cls._safe_get(lb, "specialty", cls._safe_get(lb, "craft")),
                        cls._safe_get(lb, "quantity", 1),
                        cls._safe_get(lb, "hours_per_person",
                                      cls._safe_get(t, "estimated_hours")),
                        cls._safe_get(lb, "hourly_rate_usd"),
                        cls._safe_get(lb, "company"),
                    ], labour_row)
                    labour_row += 1
            elif t.get("estimated_hours"):
                cls._write_data_row(ws_labour, [
                    f"{t.get('task_id', '')}-L1",
                    cls._safe_get(t, "task_id"),
                    "", "",
                    1,
                    cls._safe_get(t, "estimated_hours"),
                    "", "",
                ], labour_row)
                labour_row += 1

        cls._add_data_validation(ws_labour, 4, LABOUR_SPECIALTIES)

        # Sheet 3: Task_Materials
        ws_materials = wb.create_sheet("Task_Materials")
        cls._style_header(ws_materials, [
            "material_line_id", "task_id", "material_code", "description",
            "manufacturer", "part_number", "quantity", "unit_of_measure",
            "unit_price_usd", "equipment_bom_ref",
        ])
        effective_materials = list(materials)
        if not effective_materials:
            for t in tasks:
                for mr in t.get("material_resources", []):
                    if isinstance(mr, dict):
                        mr_copy = dict(mr)
                        mr_copy.setdefault("task_id", t.get("task_id", ""))
                        effective_materials.append(mr_copy)
        for i, m in enumerate(effective_materials):
            cls._write_data_row(ws_materials, [
                cls._safe_get(m, "material_line_id",
                              cls._safe_get(m, "assignment_id", f"MAT-{i+1}")),
                cls._safe_get(m, "task_id"),
                cls._safe_get(m, "material_number", cls._safe_get(m, "material_code")),
                cls._safe_get(m, "description"),
                cls._safe_get(m, "manufacturer"),
                cls._safe_get(m, "part_number"),
                cls._safe_get(m, "quantity", 1),
                cls._safe_get(m, "unit", cls._safe_get(m, "unit_of_measure", "EA")),
                cls._safe_get(m, "unit_price_usd"),
                cls._safe_get(m, "equipment_bom_ref"),
            ], i + 2)

        cls._add_data_validation(ws_materials, 8, UNITS_OF_MEASURE)

        # Sheet 4: Task_Tools
        ws_tools = wb.create_sheet("Task_Tools")
        cls._style_header(ws_tools, [
            "tool_line_id", "task_id", "item_type", "tool_code", "description",
        ])
        tools_row = 2
        for t in tasks:
            tools_list = t.get("tools", t.get("special_tools", []))
            if isinstance(tools_list, list):
                for i, tool in enumerate(tools_list):
                    if isinstance(tool, str):
                        cls._write_data_row(ws_tools, [
                            f"{t.get('task_id', '')}-T{i+1}",
                            cls._safe_get(t, "task_id"),
                            "TOOL", "", tool,
                        ], tools_row)
                        tools_row += 1
                    elif isinstance(tool, dict):
                        cls._write_data_row(ws_tools, [
                            cls._safe_get(tool, "tool_line_id",
                                          f"{t.get('task_id', '')}-T{i+1}"),
                            cls._safe_get(t, "task_id"),
                            cls._safe_get(tool, "item_type", "TOOL"),
                            cls._safe_get(tool, "tool_code"),
                            cls._safe_get(tool, "description"),
                        ], tools_row)
                        tools_row += 1

        cls._add_data_validation(ws_tools, 3, ["TOOL", "SPECIAL_EQUIPMENT"])

        for ws in wb.worksheets:
            cls._auto_size(ws)

        # Instructions
        cls._add_instructions_sheet(wb, INSTR_04_TASKS)
        return cls._save(wb, output_path)

    # ══════════════════════════════════════════════════════════════════
    # T-05: Work Packages
    # ══════════════════════════════════════════════════════════════════

    @classmethod
    def populate_05_work_packages(
        cls,
        work_packages: list[dict],
        nodes: list[dict],
        output_path: Path,
    ) -> Path:
        """Write work packages to 05_work_packages.xlsx."""
        wb = cls._create_workbook("Work Packages")
        ws = wb.active
        ws.title = "Work Packages"

        headers = [
            "wp_name", "wp_code", "equipment_tag", "frequency_value",
            "frequency_unit", "constraint", "wp_type", "access_time_hours",
            "task_ids_csv", "estimated_total_hours", "crew_size",
        ]
        cls._style_header(ws, headers)

        by_id = {n.get("node_id", ""): n for n in nodes}

        for row_num, wp in enumerate(work_packages, start=2):
            node_id = wp.get("node_id", "")
            node = by_id.get(node_id, {})
            tag = node.get("tag", node.get("code", cls._safe_get(wp, "equipment_tag")))

            task_ids = wp.get("task_ids", [])
            task_ids_csv = ",".join(task_ids) if isinstance(task_ids, list) else str(task_ids)

            cls._write_data_row(ws, [
                cls._safe_get(wp, "name", cls._safe_get(wp, "wp_name")),
                cls._safe_get(wp, "wp_id", cls._safe_get(wp, "wp_code")),
                tag,
                cls._safe_get(wp, "frequency_value",
                              cls._safe_get(wp, "frequency_days")),
                cls._safe_get(wp, "frequency_unit", "DAYS"),
                cls._safe_get(wp, "constraint"),
                cls._safe_get(wp, "wp_type", "STANDALONE"),
                cls._safe_get(wp, "access_time_hours"),
                task_ids_csv,
                cls._safe_get(wp, "estimated_hours",
                              cls._safe_get(wp, "estimated_total_hours")),
                cls._safe_get(wp, "crew_size"),
            ], row_num)

        # Data validations
        cls._add_data_validation(ws, 5, FREQUENCY_UNITS)
        cls._add_data_validation(ws, 6, WP_CONSTRAINTS)
        cls._add_data_validation(ws, 7, WP_TYPES)

        cls._auto_size(ws)
        cls._add_instructions_sheet(wb, INSTR_05_WORK_PACKAGES)
        return cls._save(wb, output_path)

    # ══════════════════════════════════════════════════════════════════
    # T-07: Spare Parts Inventory
    # ══════════════════════════════════════════════════════════════════

    @classmethod
    def populate_07_spare_parts(
        cls,
        materials: list[dict],
        output_path: Path,
    ) -> Path:
        """Write material assignments to 07_spare_parts_inventory.xlsx."""
        wb = cls._create_workbook("Spare Parts Inventory")
        ws = wb.active
        ws.title = "Spare Parts Inventory"

        headers = [
            "material_code", "description", "manufacturer", "part_number",
            "ved_class", "fsn_class", "abc_class",
            "quantity_on_hand", "min_stock", "max_stock", "reorder_point",
            "lead_time_days", "unit_cost_usd", "unit_of_measure",
            "applicable_equipment_csv", "warehouse_location",
        ]
        cls._style_header(ws, headers)

        seen: set[str] = set()
        row_num = 2
        for m in materials:
            mat_code = m.get("material_number", m.get("material_code", ""))
            if mat_code in seen:
                continue
            if mat_code:
                seen.add(mat_code)

            cls._write_data_row(ws, [
                mat_code,
                cls._safe_get(m, "description"),
                cls._safe_get(m, "manufacturer"),
                cls._safe_get(m, "part_number"),
                cls._safe_get(m, "ved_class"),
                cls._safe_get(m, "fsn_class"),
                cls._safe_get(m, "abc_class"),
                cls._safe_get(m, "quantity_on_hand", cls._safe_get(m, "quantity")),
                cls._safe_get(m, "min_stock"),
                cls._safe_get(m, "max_stock"),
                cls._safe_get(m, "reorder_point"),
                cls._safe_get(m, "lead_time_days"),
                cls._safe_get(m, "unit_cost_usd", cls._safe_get(m, "unit_price_usd")),
                cls._safe_get(m, "unit", cls._safe_get(m, "unit_of_measure", "EA")),
                cls._safe_get(m, "applicable_equipment_csv"),
                cls._safe_get(m, "warehouse_location"),
            ], row_num)
            row_num += 1

        # Data validations
        cls._add_data_validation(ws, 5, VED_CLASSES)
        cls._add_data_validation(ws, 6, FSN_CLASSES)
        cls._add_data_validation(ws, 7, ABC_CLASSES)
        cls._add_data_validation(ws, 14, UNITS_OF_MEASURE)

        cls._auto_size(ws)
        cls._add_instructions_sheet(wb, INSTR_07_SPARE_PARTS)
        return cls._save(wb, output_path)

    # ══════════════════════════════════════════════════════════════════
    # T-14: Maintenance Strategy
    # ══════════════════════════════════════════════════════════════════

    @classmethod
    def populate_14_strategy(
        cls,
        failure_modes: list[dict],
        tasks: list[dict],
        functions: list[dict],
        nodes: list[dict],
        output_path: Path,
    ) -> Path:
        """Write maintenance strategy to 14_maintenance_strategy.xlsx."""
        wb = cls._create_workbook("Maintenance Strategy")
        ws = wb.active
        ws.title = "Strategies"

        headers = [
            # Identity
            "strategy_id", "equipment_tag", "maintainable_item",
            "function_and_failure",
            # Failure Mode
            "what", "mechanism", "cause",
            # Strategy Decision
            "status", "tactics_type",
            # Primary Task
            "primary_task_id", "primary_task_interval",
            "operational_units", "time_units",
            "primary_task_acceptable_limits",
            "primary_task_conditional_comments",
            "primary_task_constraint", "primary_task_task_type",
            "primary_task_access_time",
            # Secondary Task
            "secondary_task_id", "secondary_task_constraint",
            "secondary_task_task_type", "secondary_task_access_time",
            "secondary_task_comments",
            # Budget
            "budgeted_as", "budgeted_life",
            "budgeted_life_time_units", "budgeted_life_operational_units",
            # Metadata
            "existing_task", "justification_category",
            "justification", "notes",
        ]
        cls._style_header(ws, headers)

        by_id = {n.get("node_id", ""): n for n in nodes}
        func_by_id = {f.get("function_id", ""): f for f in functions}
        task_by_id = {t.get("task_id", ""): t for t in tasks}

        for i, fm in enumerate(failure_modes):
            func = func_by_id.get(fm.get("function_id", ""), {})
            node_id = func.get("node_id", fm.get("node_id", ""))
            node = by_id.get(node_id, {})
            tag = node.get("tag", node.get("code", node_id))

            rcm = fm.get("rcm_decision", fm.get("rcm", {}))
            if isinstance(rcm, str):
                rcm = {}
            if isinstance(rcm, list):
                rcm = rcm[0] if rcm else {}
            if not isinstance(rcm, dict):
                rcm = {}

            tactics = cls._safe_get(rcm, "strategy_type",
                     cls._safe_get(rcm, "tactics_type",
                     cls._safe_get(fm, "strategy_type",
                     cls._safe_get(fm, "tactics_type"))))

            primary_task_id = cls._safe_get(rcm, "task_id",
                              cls._safe_get(fm, "primary_task_id"))
            primary_task = task_by_id.get(primary_task_id, {})

            secondary_task_id = cls._safe_get(rcm, "secondary_task_id",
                                cls._safe_get(fm, "secondary_task_id"))
            secondary_task = task_by_id.get(secondary_task_id, {})

            cls._write_data_row(ws, [
                cls._safe_get(fm, "strategy_id", f"STR-{i+1:03d}"),
                tag,
                cls._safe_get(node, "name"),
                cls._safe_get(func, "description"),
                # Failure mode
                cls._safe_get(fm, "what_component",
                              cls._safe_get(fm, "what",
                              cls._safe_get(fm, "component"))),
                cls._safe_get(fm, "mechanism"),
                cls._safe_get(fm, "cause"),
                # Decision
                "RECOMMENDED",
                tactics,
                # Primary task
                primary_task_id,
                cls._safe_get(primary_task, "frequency_value",
                              cls._safe_get(primary_task, "frequency_days",
                              cls._safe_get(rcm, "interval"))),
                cls._safe_get(primary_task, "operational_units"),
                cls._safe_get(primary_task, "frequency_unit",
                              cls._safe_get(primary_task, "time_units")),
                cls._safe_get(rcm, "acceptable_limits"),
                cls._safe_get(rcm, "conditional_comments"),
                cls._safe_get(primary_task, "constraint"),
                cls._safe_get(primary_task, "task_type",
                              cls._safe_get(primary_task, "type")),
                cls._safe_get(primary_task, "access_time_hours"),
                # Secondary task
                secondary_task_id,
                cls._safe_get(secondary_task, "constraint"),
                cls._safe_get(secondary_task, "task_type",
                              cls._safe_get(secondary_task, "type")),
                cls._safe_get(secondary_task, "access_time_hours"),
                cls._safe_get(secondary_task, "notes"),
                # Budget
                cls._safe_get(primary_task, "budgeted_as"),
                cls._safe_get(primary_task, "budgeted_life"),
                cls._safe_get(primary_task, "budgeted_life_time_units"),
                cls._safe_get(primary_task, "budgeted_life_operational_units"),
                # Metadata
                cls._safe_get(fm, "existing_task"),
                cls._safe_get(fm, "justification_category", "NEW_TASK"),
                cls._safe_get(fm, "justification"),
                cls._safe_get(fm, "notes"),
            ], i + 2)

        # Data validations — 14 columns matching standard
        cls._add_data_validation(ws, 6, MECHANISMS)
        cls._add_data_validation(ws, 7, CAUSES)
        cls._add_data_validation(ws, 8, STRATEGY_STATUSES)
        cls._add_data_validation(ws, 9, STRATEGY_TYPES)
        cls._add_data_validation(ws, 12, FREQUENCY_UNITS)
        cls._add_data_validation(ws, 13, FREQUENCY_UNITS)
        cls._add_data_validation(ws, 16, TASK_CONSTRAINTS)
        cls._add_data_validation(ws, 17, TASK_TYPES)
        cls._add_data_validation(ws, 20, TASK_CONSTRAINTS)
        cls._add_data_validation(ws, 21, TASK_TYPES)
        cls._add_data_validation(ws, 24, BUDGETED_AS_VALUES)
        cls._add_data_validation(ws, 26, BUDGETED_LIFE_UNITS)
        cls._add_data_validation(ws, 27, FREQUENCY_UNITS)
        cls._add_data_validation(ws, 29, JUSTIFICATION_CATEGORIES)

        cls._auto_size(ws)

        # Reference sheets + instructions
        cls._add_fm_combos_sheet(wb)
        cls._add_strategy_rules_sheet(wb)
        cls._add_instructions_sheet(wb, INSTR_14_STRATEGY)
        return cls._save(wb, output_path)

    # ══════════════════════════════════════════════════════════════════
    # populate_all — generates all applicable templates per milestone
    # ══════════════════════════════════════════════════════════════════

    @classmethod
    def populate_all(
        cls,
        session_entities: dict[str, list[dict]],
        output_dir: str | Path,
        plant_code: str = "",
        sap_package: dict | None = None,
    ) -> dict[str, Path]:
        """Generate all applicable template xlsx files from session entities.

        Args:
            session_entities: The session.entities dict.
            output_dir: Directory to write xlsx files into.
            plant_code: Plant code for metadata.
            sap_package: Optional SAP upload package dict.

        Returns:
            Dict mapping template filename → output Path.
        """
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        results: dict[str, Path] = {}

        nodes = session_entities.get("hierarchy_nodes", [])
        assessments = session_entities.get("criticality_assessments", [])
        functions = session_entities.get("functions", [])
        functional_failures = session_entities.get("functional_failures", [])
        failure_modes = session_entities.get("failure_modes", [])
        tasks = session_entities.get("maintenance_tasks", [])
        work_packages = session_entities.get("work_packages", [])
        materials = session_entities.get("material_assignments", [])

        # T-01: Equipment Hierarchy
        if nodes:
            try:
                results["01_equipment_hierarchy.xlsx"] = cls.populate_01_hierarchy(
                    nodes, out / "01_equipment_hierarchy.xlsx",
                )
            except Exception:
                logger.warning("Failed to populate T-01 hierarchy", exc_info=True)

        # T-02: Criticality Assessment
        if assessments:
            try:
                results["02_criticality_assessment.xlsx"] = cls.populate_02_criticality(
                    assessments, nodes, out / "02_criticality_assessment.xlsx",
                )
            except Exception:
                logger.warning("Failed to populate T-02 criticality", exc_info=True)

        # T-03: Failure Modes
        if failure_modes:
            try:
                results["03_failure_modes.xlsx"] = cls.populate_03_failure_modes(
                    failure_modes, functions, functional_failures, nodes,
                    out / "03_failure_modes.xlsx",
                )
            except Exception:
                logger.warning("Failed to populate T-03 failure modes", exc_info=True)

        # T-04: Maintenance Tasks
        if tasks:
            try:
                results["04_maintenance_tasks.xlsx"] = cls.populate_04_tasks(
                    tasks, materials, out / "04_maintenance_tasks.xlsx",
                )
            except Exception:
                logger.warning("Failed to populate T-04 tasks", exc_info=True)

        # T-05: Work Packages
        if work_packages:
            try:
                results["05_work_packages.xlsx"] = cls.populate_05_work_packages(
                    work_packages, nodes, out / "05_work_packages.xlsx",
                )
            except Exception:
                logger.warning("Failed to populate T-05 work packages", exc_info=True)

        # T-07: Spare Parts Inventory
        if materials:
            try:
                results["07_spare_parts_inventory.xlsx"] = cls.populate_07_spare_parts(
                    materials, out / "07_spare_parts_inventory.xlsx",
                )
            except Exception:
                logger.warning("Failed to populate T-07 spare parts", exc_info=True)

        # T-14: Maintenance Strategy (cross-cutting — needs FMs + tasks)
        if failure_modes:
            try:
                results["14_maintenance_strategy.xlsx"] = cls.populate_14_strategy(
                    failure_modes, tasks, functions, nodes,
                    out / "14_maintenance_strategy.xlsx",
                )
            except Exception:
                logger.warning("Failed to populate T-14 strategy", exc_info=True)

        logger.info(
            "Template population complete: %d/%d templates generated in %s",
            len(results), 7, out,
        )
        return results
