"""Process completed AMS RFI questionnaire Excel into project configuration.

Reads a filled-in RFI questionnaire (generated by generate_rfi_template.py),
validates it, and generates:
  - project.yaml
  - data-availability-report.md
  - scope-assessment.md
  - 3-memory/global-requirements.md
  - rfi-followup.md (if missing data)

Usage:
    python scripts/process_ams_rfi.py filled-rfi.xlsx --client ocp --project jfc-maintenance-strategy
    python scripts/process_ams_rfi.py filled-rfi.xlsx --client ocp --project jfc --scaffold
    python scripts/process_ams_rfi.py filled-rfi.xlsx --client ocp --project jfc --dry-run
"""

from __future__ import annotations

import argparse
import logging
import re
import sys
from datetime import date, datetime
from pathlib import Path
from typing import Any

import yaml
from openpyxl import load_workbook

# Ensure project root is importable
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from agents._shared.paths import (  # noqa: E402
    get_intent_specs_dir,
    get_memory_dir,
    get_output_dir,
    get_project_root,
    scaffold_project,
)
from tools.models.rfi_models import (  # noqa: E402
    AMS_TEMPLATES,
    CMMSType,
    CriticalityMethodRFI,
    CompanySiteProfile,
    DataAvailabilityChecklist,
    DataAvailabilityItem,
    DataFormat,
    EquipmentHierarchyData,
    Industry,
    KPIBaselineTargets,
    Language,
    MaintenanceCurrentState,
    OrgStructure,
    OrganizationResources,
    RFISubmission,
    SAPVersion,
    ScopeTimeline,
    ScopeType,
    StandardsCompliance,
    StrategyMaturity,
    WorkshopFormat,
)
from tools.validators.rfi_validator import RFIValidator  # noqa: E402

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Safe cell readers (pattern from OR SYSTEM)
# ---------------------------------------------------------------------------

def _safe_str(value: Any) -> str:
    """Convert cell value to stripped string, empty string for None."""
    if value is None:
        return ""
    return str(value).strip()


def _safe_int(value: Any, default: int | None = None) -> int | None:
    """Convert cell value to int, returning default for invalid/empty."""
    if value is None:
        return default
    try:
        return int(float(value))
    except (ValueError, TypeError):
        return default


def _safe_float(value: Any, default: float | None = None) -> float | None:
    """Convert cell value to float, returning default for invalid/empty."""
    if value is None:
        return default
    try:
        return float(value)
    except (ValueError, TypeError):
        return default


def _safe_bool(value: Any) -> bool | None:
    """Convert cell value to bool. Recognizes Yes/No/True/False/Partial."""
    if value is None:
        return None
    s = str(value).strip().lower()
    if s in ("yes", "true", "1", "partial"):
        return True
    if s in ("no", "false", "0"):
        return False
    return None


def _split_list(value: Any, sep: str = ";") -> list[str]:
    """Split cell value into list, stripping whitespace."""
    if value is None:
        return []
    return [item.strip() for item in str(value).split(sep) if item.strip()]


def _safe_date(value: Any) -> date | None:
    """Convert cell value to date."""
    if value is None:
        return None
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    try:
        return datetime.strptime(str(value).strip(), "%Y-%m-%d").date()
    except (ValueError, TypeError):
        return None


def _safe_enum(value: Any, enum_cls: type) -> Any:
    """Convert cell value to enum member, returning None if invalid."""
    s = _safe_str(value)
    if not s:
        return None
    # Try direct match
    for member in enum_cls:
        if member.value == s:
            return member
    # Try case-insensitive
    s_lower = s.lower()
    for member in enum_cls:
        if member.value.lower() == s_lower:
            return member
    return None


# ---------------------------------------------------------------------------
# Response column index (column C = index 3 in openpyxl)
# ---------------------------------------------------------------------------

_RESPONSE_COL = 3  # Column C


def _get_responses(ws) -> dict[str, Any]:
    """Extract field_id -> response value mapping from a questionnaire sheet.

    Reads rows starting from row 2. Column A = field ID, Column C = response.
    """
    responses: dict[str, Any] = {}
    for row in ws.iter_rows(min_row=2, max_col=6, values_only=False):
        field_id = _safe_str(row[0].value)  # Column A
        if not field_id:
            continue
        responses[field_id] = row[_RESPONSE_COL - 1].value  # Column C
    return responses


# ---------------------------------------------------------------------------
# Per-sheet parsers
# ---------------------------------------------------------------------------

def parse_company_site(ws) -> CompanySiteProfile:
    """Parse Sheet 1: Company & Site Profile."""
    r = _get_responses(ws)
    return CompanySiteProfile(
        company_name=_safe_str(r.get("CSP-01")),
        industry=_safe_enum(r.get("CSP-02"), Industry),
        plant_name=_safe_str(r.get("CSP-03")),
        plant_code=_safe_str(r.get("CSP-04")),
        location=_safe_str(r.get("CSP-05")),
        country=_safe_str(r.get("CSP-06")),
        production_capacity=_safe_str(r.get("CSP-07")),
        primary_language=_safe_enum(r.get("CSP-08"), Language),
        secondary_language=_safe_enum(r.get("CSP-09"), Language),
        contact_name=_safe_str(r.get("CSP-10")),
        contact_email=_safe_str(r.get("CSP-11")),
        contact_phone=_safe_str(r.get("CSP-12")),
    )


def parse_equipment_hierarchy(ws) -> EquipmentHierarchyData:
    """Parse Sheet 2: Equipment & Hierarchy Data."""
    r = _get_responses(ws)
    return EquipmentHierarchyData(
        equipment_list_available=_safe_bool(r.get("EHD-01")),
        equipment_list_format=_safe_enum(r.get("EHD-02"), DataFormat),
        estimated_equipment_count=_safe_int(r.get("EHD-03")),
        hierarchy_levels=_safe_int(r.get("EHD-04")),
        naming_convention=_safe_str(r.get("EHD-05")),
        naming_convention_document=_safe_bool(r.get("EHD-06")),
        bom_available=_safe_bool(r.get("EHD-07")),
        bom_format=_safe_enum(r.get("EHD-08"), DataFormat),
        tag_format_example=_safe_str(r.get("EHD-09")),
        functional_location_structure=_safe_str(r.get("EHD-10")),
        equipment_master_in_sap=_safe_bool(r.get("EHD-11")),
    )


def parse_maintenance_state(ws) -> MaintenanceCurrentState:
    """Parse Sheet 3: Maintenance Current State."""
    r = _get_responses(ws)
    return MaintenanceCurrentState(
        strategy_maturity=_safe_enum(r.get("MCS-01"), StrategyMaturity),
        cmms_type=_safe_enum(r.get("MCS-02"), CMMSType),
        sap_version=_safe_enum(r.get("MCS-03"), SAPVersion),
        wo_history_available=_safe_bool(r.get("MCS-04")),
        wo_history_years=_safe_int(r.get("MCS-05")),
        failure_data_available=_safe_bool(r.get("MCS-06")),
        failure_data_format=_safe_enum(r.get("MCS-07"), DataFormat),
        downtime_tracking=_safe_bool(r.get("MCS-08")),
        planned_maintenance_exists=_safe_bool(r.get("MCS-09")),
        pm_plan_format=_safe_enum(r.get("MCS-10"), DataFormat),
        prior_criticality_assessment=_safe_bool(r.get("MCS-11")),
        criticality_method=_safe_enum(r.get("MCS-12"), CriticalityMethodRFI),
        prior_fmeca=_safe_bool(r.get("MCS-13")),
        prior_rcm_study=_safe_bool(r.get("MCS-14")),
    )


def parse_organization(ws) -> OrganizationResources:
    """Parse Sheet 4: Organization & Resources."""
    r = _get_responses(ws)
    return OrganizationResources(
        team_size=_safe_int(r.get("ORG-01")),
        org_structure=_safe_enum(r.get("ORG-02"), OrgStructure),
        shifts=_safe_int(r.get("ORG-03")),
        contractor_maintenance=_safe_bool(r.get("ORG-04")),
        trades=_split_list(r.get("ORG-05")),
        dedicated_planner=_safe_bool(r.get("ORG-06")),
        dedicated_reliability_engineer=_safe_bool(r.get("ORG-07")),
        maintenance_budget_usd=_safe_float(r.get("ORG-08")),
    )


def parse_standards(ws) -> StandardsCompliance:
    """Parse Sheet 5: Standards & Compliance."""
    r = _get_responses(ws)
    return StandardsCompliance(
        iso_certifications=_split_list(r.get("STD-01")),
        industry_regulations=_split_list(r.get("STD-02")),
        lototo_program=_safe_bool(r.get("STD-03")),
        procedure_documentation=_safe_bool(r.get("STD-04")),
        procedure_language=_safe_enum(r.get("STD-05"), Language),
        safety_permits_required=_split_list(r.get("STD-06")),
        ppe_matrix=_safe_bool(r.get("STD-07")),
        environmental_permits=_split_list(r.get("STD-08")),
    )


def parse_kpi_baseline(ws) -> KPIBaselineTargets:
    """Parse Sheet 6: KPI Baseline & Targets."""
    r = _get_responses(ws)
    return KPIBaselineTargets(
        current_availability=_safe_float(r.get("KPI-01")),
        target_availability=_safe_float(r.get("KPI-02")),
        current_mtbf_hours=_safe_float(r.get("KPI-03")),
        current_mttr_hours=_safe_float(r.get("KPI-04")),
        current_oee=_safe_float(r.get("KPI-05")),
        annual_maintenance_cost_usd=_safe_float(r.get("KPI-06")),
        current_planned_vs_unplanned=_safe_float(r.get("KPI-07")),
        target_planned_vs_unplanned=_safe_float(r.get("KPI-08")),
        current_pm_compliance=_safe_float(r.get("KPI-09")),
        target_pm_compliance=_safe_float(r.get("KPI-10")),
    )


def parse_scope_timeline(ws) -> ScopeTimeline:
    """Parse Sheet 7: Scope & Timeline."""
    r = _get_responses(ws)
    return ScopeTimeline(
        scope_type=_safe_enum(r.get("SCT-01"), ScopeType),
        areas_in_scope=_split_list(r.get("SCT-02")),
        priority_equipment=_split_list(r.get("SCT-03")),
        start_date=_safe_date(r.get("SCT-04")),
        target_completion=_safe_date(r.get("SCT-05")),
        deliverables=_split_list(r.get("SCT-06")),
        workshop_format=_safe_enum(r.get("SCT-07"), WorkshopFormat),
    )


def parse_data_availability(ws) -> DataAvailabilityChecklist:
    """Parse Sheet 8: Data Availability Checklist."""
    items: list[DataAvailabilityItem] = []
    for row in ws.iter_rows(min_row=2, max_col=6, values_only=False):
        template_id = _safe_str(row[0].value)
        if not template_id:
            continue
        template_name = _safe_str(row[1].value)
        items.append(DataAvailabilityItem(
            template_id=template_id,
            template_name=template_name,
            available=_safe_bool(row[2].value),
            data_format=_safe_enum(row[3].value, DataFormat),
            quality_score=_safe_int(row[4].value),
            notes=_safe_str(row[5].value),
        ))
    return DataAvailabilityChecklist(items=items)


# ---------------------------------------------------------------------------
# Output generators
# ---------------------------------------------------------------------------

def _slugify(text: str) -> str:
    """Convert text to a URL-friendly slug."""
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_]+", "-", text)
    text = re.sub(r"-+", "-", text)
    return text.strip("-")


def _val_or_none(v: Any) -> Any:
    """Return value or None if empty string."""
    if isinstance(v, str) and v == "":
        return None
    return v


def build_project_yaml(submission: RFISubmission) -> dict:
    """Build project.yaml dict from RFI data. Matches OCP reference format."""
    s = submission
    cs = s.company_site
    ms = s.maintenance_state
    kpi = s.kpi_baseline
    st = s.scope_timeline
    org = s.organization
    std = s.standards

    def _enum_val(e: Any) -> str | None:
        return e.value if e is not None else None

    # Determine availability target as fraction (0-1)
    availability_target = None
    if kpi.target_availability is not None:
        availability_target = round(kpi.target_availability / 100, 2)

    # Check template availability
    def _template_available(tid: str) -> bool:
        for item in s.data_availability.items:
            if item.template_id == tid and item.available is True:
                return True
        return False

    return {
        "project": {
            "id": f"{_slugify(cs.country or 'xx')}-{_slugify(cs.plant_name or 'unknown')}-001",
            "name": f"{cs.plant_name} Maintenance Strategy Development" if cs.plant_name else "Maintenance Strategy Development",
            "version": "1.0",
            "created_at": date.today().isoformat(),
        },
        "client": {
            "slug": _slugify(cs.company_name) if cs.company_name else "",
            "name": _val_or_none(cs.company_name),
            "industry": _enum_val(cs.industry),
            "country": _val_or_none(cs.country),
            "language": _enum_val(cs.primary_language),
        },
        "scope": {
            "type": _enum_val(st.scope_type),
            "plant": {
                "name": _val_or_none(cs.plant_name),
                "code": _val_or_none(cs.plant_code),
                "location": _val_or_none(cs.location),
            },
            "priority_equipment": st.priority_equipment or [],
            "timeline": {
                "start_date": st.start_date.isoformat() if st.start_date else None,
                "target_completion": st.target_completion.isoformat() if st.target_completion else None,
            },
            "areas_in_scope": st.areas_in_scope or [],
        },
        "maintenance_context": {
            "strategy_maturity": _enum_val(ms.strategy_maturity),
            "cmms": _enum_val(ms.cmms_type),
            "sap_version": _enum_val(ms.sap_version),
            "criticality_method": _enum_val(ms.criticality_method),
            "availability_target": availability_target,
            "existing_data": {
                "equipment_list": s.equipment_hierarchy.equipment_list_available or False,
                "failure_history": ms.failure_data_available or False,
                "existing_pm_plans": ms.planned_maintenance_exists or False,
                "spare_parts_inventory": _template_available("07_spare_parts_inventory"),
                "bom_data": s.equipment_hierarchy.bom_available or False,
            },
        },
        "organization": {
            "team_size": org.team_size,
            "structure": _enum_val(org.org_structure),
            "shifts": org.shifts,
            "trades": org.trades or [],
        },
        "standards": {
            "iso_certifications": std.iso_certifications or [],
            "safety_requirements": std.safety_permits_required or [],
            "procedure_language": _enum_val(std.procedure_language),
        },
        "kpi_baseline": {
            "availability": kpi.current_availability,
            "mtbf_hours": kpi.current_mtbf_hours,
            "mttr_hours": kpi.current_mttr_hours,
            "oee": kpi.current_oee,
            "planned_vs_unplanned": kpi.current_planned_vs_unplanned,
            "pm_compliance": kpi.current_pm_compliance,
        },
    }


def generate_data_availability_report(submission: RFISubmission) -> str:
    """Generate data-availability-report.md markdown content."""
    lines = [
        "# Data Availability Report",
        "",
        f"Generated: {date.today().isoformat()}",
        f"Client: {submission.company_site.company_name}",
        f"Plant: {submission.company_site.plant_name}",
        "",
        "## Data Availability Matrix",
        "",
        "| Template | Available | Format | Quality | Notes |",
        "|----------|-----------|--------|---------|-------|",
    ]

    available_count = 0
    for item in submission.data_availability.items:
        avail = "Yes" if item.available else ("No" if item.available is False else "?")
        if item.available:
            available_count += 1
        fmt = item.data_format.value if item.data_format else "-"
        quality = str(item.quality_score) if item.quality_score else "-"
        notes = item.notes or "-"
        lines.append(f"| {item.template_name} | {avail} | {fmt} | {quality} | {notes} |")

    total = len(submission.data_availability.items) or 1
    pct = (available_count / total) * 100

    lines.extend([
        "",
        "## Summary",
        "",
        f"- **Data available**: {available_count}/{total} templates ({pct:.0f}%)",
        f"- **Data gaps**: {total - available_count} templates without data",
    ])

    return "\n".join(lines)


def generate_scope_assessment(submission: RFISubmission) -> str:
    """Generate scope-assessment.md with effort estimation."""
    cs = submission.company_site
    st = submission.scope_timeline
    eh = submission.equipment_hierarchy
    ms = submission.maintenance_state

    equip_count = eh.estimated_equipment_count or 0
    scope = st.scope_type.value if st.scope_type else "unknown"

    # Simple effort heuristics
    if equip_count <= 50:
        complexity = "Low"
    elif equip_count <= 200:
        complexity = "Medium"
    elif equip_count <= 500:
        complexity = "High"
    else:
        complexity = "Very High"

    has_history = ms.wo_history_available or False
    has_criticality = ms.prior_criticality_assessment or False
    has_fmeca = ms.prior_fmeca or False

    available_data = sum(
        1 for item in submission.data_availability.items if item.available
    )

    lines = [
        "# Scope Assessment",
        "",
        f"Generated: {date.today().isoformat()}",
        f"Client: {cs.company_name}",
        f"Plant: {cs.plant_name}",
        "",
        "## Scope Summary",
        "",
        f"- **Scope type**: {scope}",
        f"- **Equipment count**: {equip_count}",
        f"- **Complexity**: {complexity}",
        f"- **Areas**: {', '.join(st.areas_in_scope) if st.areas_in_scope else 'Not specified'}",
        f"- **Priority equipment**: {', '.join(st.priority_equipment) if st.priority_equipment else 'Not specified'}",
        "",
        "## Starting Point Assessment",
        "",
        f"- Existing WO history: {'Yes' if has_history else 'No'}",
        f"- Prior criticality assessment: {'Yes' if has_criticality else 'No'}",
        f"- Prior FMECA: {'Yes' if has_fmeca else 'No'}",
        f"- Data templates available: {available_data}/14",
        "",
        "## Timeline",
        "",
        f"- Start: {st.start_date.isoformat() if st.start_date else 'TBD'}",
        f"- Target completion: {st.target_completion.isoformat() if st.target_completion else 'TBD'}",
        "",
        "## Recommended Starting Milestone",
        "",
    ]

    if has_criticality and has_fmeca:
        lines.append("Start at **Milestone 3** (Strategy + Tasks) — prior criticality and FMECA exist.")
    elif has_criticality:
        lines.append("Start at **Milestone 2** (FMEA) — prior criticality exists, skip hierarchy.")
    else:
        lines.append("Start at **Milestone 1** (Hierarchy + Criticality) — full analysis required.")

    return "\n".join(lines)


def generate_global_requirements(submission: RFISubmission) -> str:
    """Generate global-requirements.md seeded with RFI data."""
    cs = submission.company_site
    std = submission.standards

    lang = cs.primary_language.value if cs.primary_language else "en"
    proc_lang = std.procedure_language.value if std.procedure_language else lang

    lines = [
        "# Global Requirements",
        "",
        f"Generated from RFI: {date.today().isoformat()}",
        "",
        "## Language",
        "",
        f"- Primary language: {lang}",
        f"- Procedure language: {proc_lang}",
        f"- Work instructions MUST be written in: **{proc_lang}**",
    ]

    if cs.secondary_language:
        lines.append(f"- Secondary language: {cs.secondary_language.value}")

    lines.extend(["", "## Naming Conventions", ""])

    eh = submission.equipment_hierarchy
    if eh.naming_convention:
        lines.append(f"- Convention: {eh.naming_convention}")
    if eh.tag_format_example:
        lines.append(f"- Tag example: {eh.tag_format_example}")
    if eh.functional_location_structure:
        lines.append(f"- Functional location: {eh.functional_location_structure}")
    if not eh.naming_convention and not eh.tag_format_example:
        lines.append("- No naming convention specified — use AMS defaults")

    lines.extend(["", "## Standards", ""])

    if std.iso_certifications:
        lines.append(f"- ISO certifications: {', '.join(std.iso_certifications)}")
    if std.safety_permits_required:
        lines.append(f"- Safety permits: {', '.join(std.safety_permits_required)}")
    if std.lototo_program:
        lines.append("- LOTOTO program: Active")
    if std.industry_regulations:
        lines.append(f"- Industry regulations: {', '.join(std.industry_regulations)}")

    lines.extend(["", "## Criticality Method", ""])

    ms = submission.maintenance_state
    if ms.criticality_method:
        lines.append(f"- Method: {ms.criticality_method.value}")
        lines.append("- Override allowed: No")
    else:
        lines.append("- Method: Not specified — use R8 + GFSN default")

    lines.extend(["", "## CMMS Integration", ""])

    if ms.cmms_type:
        lines.append(f"- CMMS: {ms.cmms_type.value}")
    if ms.sap_version:
        lines.append(f"- SAP version: {ms.sap_version.value}")
    if ms.cmms_type == CMMSType.SAP_PM:
        lines.append("- SAP field length constraints apply to all outputs")

    lines.extend(["", "## Hard Constraints", ""])
    lines.append("<!-- Non-negotiable constraints that override ALL methodology defaults. -->")

    st = submission.scope_timeline
    if hasattr(st, "constraints") and st.constraints:
        for constraint in st.constraints:
            lines.append(f"- {constraint}")
    else:
        lines.append("- None specified")

    return "\n".join(lines)


def generate_maintenance_strategy_requirements(submission: RFISubmission) -> str:
    """Generate maintenance-strategy/requirements.md from Sheet 3 + Sheet 7 data."""
    ms = submission.maintenance_state
    st = submission.scope_timeline

    lines = [
        "# Maintenance Strategy Requirements",
        "",
        f"Generated from RFI: {date.today().isoformat()}",
        "",
        "## Current State (Sheet 3)",
        "",
        f"- Strategy maturity: {ms.strategy_maturity.value if ms.strategy_maturity else 'Not specified'}",
        f"- CMMS: {ms.cmms_type.value if ms.cmms_type else 'Not specified'}",
        f"- WO history available: {'Yes' if ms.wo_history_available else 'No'}",
        f"- WO history years: {ms.wo_history_years or 'Not specified'}",
        f"- Failure data available: {'Yes' if ms.failure_data_available else 'No'}",
        f"- Downtime tracking: {'Yes' if ms.downtime_tracking else 'No'}",
        f"- Planned maintenance exists: {'Yes' if ms.planned_maintenance_exists else 'No'}",
        f"- Prior criticality: {'Yes' if ms.prior_criticality_assessment else 'No'}",
        f"- Criticality method: {ms.criticality_method.value if ms.criticality_method else 'Not specified'}",
        f"- Prior FMECA: {'Yes' if ms.prior_fmeca else 'No'}",
        f"- Prior RCM study: {'Yes' if ms.prior_rcm_study else 'No'}",
        "",
        "## Scope & Priorities (Sheet 7)",
        "",
        f"- Scope type: {st.scope_type.value if st.scope_type else 'Not specified'}",
        f"- Areas in scope: {', '.join(st.areas_in_scope) if st.areas_in_scope else 'Not specified'}",
        f"- Priority equipment: {', '.join(st.priority_equipment) if st.priority_equipment else 'Not specified'}",
        f"- Deliverables: {', '.join(st.deliverables) if st.deliverables else 'Not specified'}",
        f"- Workshop format: {st.workshop_format.value if st.workshop_format else 'Not specified'}",
    ]
    if st.start_date:
        lines.append(f"- Start date: {st.start_date.isoformat()}")
    if st.target_completion:
        lines.append(f"- Target completion: {st.target_completion.isoformat()}")

    return "\n".join(lines)


def generate_work_planning_requirements(submission: RFISubmission) -> str:
    """Generate work-planning/requirements.md from Sheet 4 data."""
    org = submission.organization

    lines = [
        "# Work Planning Requirements",
        "",
        f"Generated from RFI: {date.today().isoformat()}",
        "",
        "## Organization & Resources (Sheet 4)",
        "",
        f"- Team size: {org.team_size or 'Not specified'}",
        f"- Org structure: {org.org_structure.value if org.org_structure else 'Not specified'}",
        f"- Shifts: {org.shifts or 'Not specified'}",
        f"- Contractor maintenance: {'Yes' if org.contractor_maintenance else 'No'}",
        f"- Trades: {', '.join(org.trades) if org.trades else 'Not specified'}",
        f"- Dedicated planner: {'Yes' if org.dedicated_planner else 'No'}",
        f"- Dedicated reliability engineer: {'Yes' if org.dedicated_reliability_engineer else 'No'}",
    ]
    if org.maintenance_budget_usd:
        lines.append(f"- Budget: ${org.maintenance_budget_usd:,.0f}")
    else:
        lines.append("- Budget: Not specified")

    return "\n".join(lines)


def generate_reliability_requirements(submission: RFISubmission) -> str:
    """Generate reliability-engineering/requirements.md from data availability."""
    ms = submission.maintenance_state

    lines = [
        "# Reliability Engineering Requirements",
        "",
        f"Generated from RFI: {date.today().isoformat()}",
        "",
        "## Data Availability",
        "",
        f"- Work order history available: {'Yes' if ms.wo_history_available else 'No'}",
        f"- WO history years: {ms.wo_history_years or 'Not specified'}",
        f"- Failure data available: {'Yes' if ms.failure_data_available else 'No'}",
        f"- Downtime tracking: {'Yes' if ms.downtime_tracking else 'No'}",
        "",
        "## Analysis Scope",
        "",
    ]
    if ms.prior_rcm_study:
        lines.append("- Prior RCM study exists — review before new analysis")
    if ms.prior_fmeca:
        lines.append("- Prior FMECA exists — review before new analysis")
    if ms.wo_history_available and ms.wo_history_years and ms.wo_history_years >= 3:
        lines.append("- Sufficient WO history for Weibull fitting")
    else:
        lines.append("- Limited WO history — use engineering estimates")

    return "\n".join(lines)


def generate_cost_analysis_requirements(submission: RFISubmission) -> str:
    """Generate cost-analysis/requirements.md from KPI baseline data."""
    kpi = submission.kpi_baseline
    org = submission.organization

    lines = [
        "# Cost Analysis Requirements",
        "",
        f"Generated from RFI: {date.today().isoformat()}",
        "",
        "## Cost Baseline",
        "",
    ]
    if kpi.annual_maintenance_cost_usd is not None:
        lines.append(f"- Annual maintenance cost: ${kpi.annual_maintenance_cost_usd:,.0f}")
    else:
        lines.append("- Annual maintenance cost: Not specified")
    if org.maintenance_budget_usd:
        lines.append(f"- Maintenance budget: ${org.maintenance_budget_usd:,.0f}")
    if kpi.target_availability is not None:
        lines.append(f"- Target availability: {kpi.target_availability}%")
    if kpi.target_pm_compliance is not None:
        lines.append(f"- Target PM compliance: {kpi.target_pm_compliance}%")

    return "\n".join(lines)


def generate_standards_appendix(submission: RFISubmission) -> str:
    """Generate appendix for global-requirements.md from Sheet 5 HSE data."""
    std = submission.standards

    lines = [
        "",
        "## HSE & Environmental (from RFI Sheet 5)",
        "",
        f"- PPE matrix documented: {'Yes' if std.ppe_matrix else 'No'}",
        f"- Procedure documentation: {'Yes' if std.procedure_documentation else 'No'}",
    ]
    if std.environmental_permits:
        lines.append(f"- Environmental permits: {', '.join(std.environmental_permits)}")
    if std.safety_permits_required:
        lines.append(f"- Safety permits: {', '.join(std.safety_permits_required)}")

    return "\n".join(lines)


def generate_kpi_appendix(submission: RFISubmission) -> str:
    """Generate appendix for global-requirements.md from Sheet 6 KPI targets."""
    kpi = submission.kpi_baseline

    lines = [
        "",
        "## KPI Targets (from RFI Sheet 6)",
        "",
    ]
    if kpi.target_availability is not None:
        lines.append(f"- Target availability: {kpi.target_availability}%")
    else:
        lines.append("- Target availability: Not specified")
    if kpi.target_planned_vs_unplanned is not None:
        lines.append(f"- Target planned/unplanned: {kpi.target_planned_vs_unplanned}%")
    else:
        lines.append("- Target planned/unplanned: Not specified")
    if kpi.target_pm_compliance is not None:
        lines.append(f"- Target PM compliance: {kpi.target_pm_compliance}%")
    else:
        lines.append("- Target PM compliance: Not specified")
    if kpi.annual_maintenance_cost_usd is not None:
        lines.append(f"- Annual maintenance cost: ${kpi.annual_maintenance_cost_usd:,.0f}")
    else:
        lines.append("- Annual maintenance cost: Not specified")

    return "\n".join(lines)


def _generate_intent_profile(
    submission: "RFISubmission",
    client_slug: str,
    project_slug: str,
) -> None:
    """Generate a minimal intent-profile.yaml from RFI responses (IP-L1 only).

    IP-L2 and IP-L3 are left empty — they require a client interview.
    """
    summary: dict[str, Any] = {
        "client": getattr(submission.company_site, "company_name", client_slug),
        "project": getattr(submission.company_site, "plant_name", project_slug),
        "trade_off_priority": ["safety", "availability", "cost"],
        "risk_appetite": "moderate",
        "primary_kpi": "availability",
        "primary_kpi_target": 90,
        "hard_limits": [],
    }

    # Extract from KPI section if available
    kpi = getattr(submission, "kpi_baseline", None)
    if kpi:
        if getattr(kpi, "primary_kpi", None):
            summary["primary_kpi"] = kpi.primary_kpi
        if getattr(kpi, "primary_target", None):
            summary["primary_kpi_target"] = kpi.primary_target

    profile = {
        "schema_version": "1.0",
        "intent_summary": summary,
        "domain_intent": {
            "reliability": {},
            "planning": {},
            "spare_parts": {},
        },
        "full_context": {},
        "trade_off_matrix": [],
        "veto_rules": [],
    }

    intent_dir = get_intent_specs_dir(client_slug, project_slug)
    intent_dir.mkdir(parents=True, exist_ok=True)
    intent_file = intent_dir / "intent-profile.yaml"
    with open(intent_file, "w", encoding="utf-8") as f:
        yaml.dump(profile, f, default_flow_style=False, allow_unicode=True)
    logger.info("Generated intent profile: %s", intent_file)


def _append_or_create(path: Path, content: str, dry_run: bool = False) -> None:
    """Append content to file if it exists, create if not. Never overwrites.

    Idempotent: does not duplicate content if already present.
    """
    if dry_run:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if content.strip() not in existing:
            with open(path, "a", encoding="utf-8") as f:
                f.write("\n\n" + content)
            logger.info("Appended to: %s", path)
    else:
        path.write_text(content, encoding="utf-8")
        logger.info("Created: %s", path)


def generate_followup(
    submission: RFISubmission,
    validation_results: list,
) -> str | None:
    """Generate rfi-followup.md for missing required data.

    Returns None if no followup is needed (all required fields filled).
    """
    errors = [r for r in validation_results if r.severity == "ERROR"]
    warnings = [r for r in validation_results if r.severity == "WARNING"]

    if not errors and not warnings:
        return None

    lines = [
        "# RFI Follow-Up Items",
        "",
        f"Generated: {date.today().isoformat()}",
        f"Client: {submission.company_site.company_name}",
        "",
    ]

    if errors:
        lines.extend([
            "## Required Items (MUST resolve before proceeding)",
            "",
        ])
        for r in errors:
            lines.append(f"- **[{r.rule_id}]** {r.message}")
        lines.append("")

    if warnings:
        lines.extend([
            "## Recommended Items (improve quality)",
            "",
        ])
        for r in warnings:
            lines.append(f"- [{r.rule_id}] {r.message}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main processing function
# ---------------------------------------------------------------------------

def process_rfi(
    excel_path: Path,
    client_slug: str,
    project_slug: str,
    scaffold: bool = False,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Process a filled RFI Excel into project configuration files.

    Args:
        excel_path: Path to the completed RFI Excel file.
        client_slug: Client identifier (e.g., 'ocp').
        project_slug: Project identifier (e.g., 'jfc-maintenance-strategy').
        scaffold: If True, create project directory structure first.
        dry_run: If True, validate and generate content but don't write files.

    Returns:
        Dict with 'files' (dict of path->content), 'validation' (list),
        'completeness_score' (float).
    """
    excel_path = Path(excel_path).resolve()
    if not excel_path.exists():
        raise FileNotFoundError(f"RFI Excel not found: {excel_path}")
    if not excel_path.suffix.lower() == ".xlsx":
        raise ValueError(f"Expected .xlsx file, got: {excel_path.suffix}")

    # Scaffold project if requested
    if scaffold and not dry_run:
        scaffold_project(client_slug, project_slug)

    # Load workbook (data_only=True to read calculated values)
    wb = load_workbook(str(excel_path), data_only=True)

    # Parse all sheets (by title prefix matching)
    submission = RFISubmission(
        company_site=parse_company_site(_find_sheet(wb, "1-Company")),
        equipment_hierarchy=parse_equipment_hierarchy(_find_sheet(wb, "2-Equipment")),
        maintenance_state=parse_maintenance_state(_find_sheet(wb, "3-Maintenance")),
        organization=parse_organization(_find_sheet(wb, "4-Organization")),
        standards=parse_standards(_find_sheet(wb, "5-Standards")),
        kpi_baseline=parse_kpi_baseline(_find_sheet(wb, "6-KPI")),
        scope_timeline=parse_scope_timeline(_find_sheet(wb, "7-Scope")),
        data_availability=parse_data_availability(_find_sheet(wb, "8-Data")),
    )

    # Validate
    validation_results = RFIValidator.run_full_validation(submission)
    score, _ = RFIValidator.calculate_completeness(submission)

    # Generate outputs
    project_yaml_dict = build_project_yaml(submission)
    project_yaml_str = yaml.dump(
        project_yaml_dict,
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
    )
    availability_report = generate_data_availability_report(submission)
    scope_assessment = generate_scope_assessment(submission)
    global_requirements = generate_global_requirements(submission)
    followup = generate_followup(submission, validation_results)

    # Generate memory-seeding content from remaining RFI sheets
    maint_strategy_req = generate_maintenance_strategy_requirements(submission)
    work_planning_req = generate_work_planning_requirements(submission)
    reliability_req = generate_reliability_requirements(submission)
    cost_analysis_req = generate_cost_analysis_requirements(submission)
    standards_appendix = generate_standards_appendix(submission)
    kpi_appendix = generate_kpi_appendix(submission)

    # Resolve output paths
    project_root = get_project_root(client_slug, project_slug)
    output_dir = get_output_dir(client_slug, project_slug)
    memory_dir = get_memory_dir(client_slug, project_slug)

    rfi_output_dir = output_dir / "rfi"

    files: dict[str, str] = {
        str(project_root / "project.yaml"): project_yaml_str,
        str(rfi_output_dir / "data-availability-report.md"): availability_report,
        str(rfi_output_dir / "scope-assessment.md"): scope_assessment,
        str(memory_dir / "global-requirements.md"): global_requirements,
    }
    if followup:
        files[str(rfi_output_dir / "rfi-followup.md")] = followup

    # Write files (unless dry run)
    if not dry_run:
        for path_str, content in files.items():
            p = Path(path_str)
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content, encoding="utf-8")
            logger.info("Wrote: %s", p)

    # Phase 9: Seed additional memory files (append-only, idempotent)
    _append_or_create(
        memory_dir / "maintenance-strategy" / "requirements.md",
        maint_strategy_req,
        dry_run=dry_run,
    )
    _append_or_create(
        memory_dir / "work-planning" / "requirements.md",
        work_planning_req,
        dry_run=dry_run,
    )
    _append_or_create(
        memory_dir / "global-requirements.md",
        standards_appendix,
        dry_run=dry_run,
    )
    _append_or_create(
        memory_dir / "global-requirements.md",
        kpi_appendix,
        dry_run=dry_run,
    )
    _append_or_create(
        memory_dir / "reliability-engineering" / "requirements.md",
        reliability_req,
        dry_run=dry_run,
    )
    _append_or_create(
        memory_dir / "cost-analysis" / "requirements.md",
        cost_analysis_req,
        dry_run=dry_run,
    )

    # Generate intent profile from RFI data (IP-L1 only)
    if not dry_run:
        _generate_intent_profile(submission, client_slug, project_slug)

    # Add memory-seeded files to result tracking
    memory_files = {
        str(memory_dir / "maintenance-strategy" / "requirements.md"): maint_strategy_req,
        str(memory_dir / "work-planning" / "requirements.md"): work_planning_req,
        str(memory_dir / "reliability-engineering" / "requirements.md"): reliability_req,
        str(memory_dir / "cost-analysis" / "requirements.md"): cost_analysis_req,
    }
    files.update(memory_files)

    return {
        "files": files,
        "validation": [
            {"rule_id": r.rule_id, "severity": r.severity, "message": r.message}
            for r in validation_results
        ],
        "completeness_score": score,
    }


def _find_sheet(wb, prefix: str):
    """Find worksheet by title prefix (case-insensitive)."""
    prefix_lower = prefix.lower()
    for ws in wb.worksheets:
        if ws.title.lower().startswith(prefix_lower):
            return ws
    raise ValueError(f"Sheet with prefix '{prefix}' not found in workbook")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Process completed AMS RFI questionnaire",
    )
    parser.add_argument(
        "input_excel",
        type=Path,
        help="Path to the completed RFI Excel file (.xlsx)",
    )
    parser.add_argument(
        "--client", "-c",
        required=True,
        help="Client slug (e.g., 'ocp')",
    )
    parser.add_argument(
        "--project", "-p",
        required=True,
        help="Project slug (e.g., 'jfc-maintenance-strategy')",
    )
    parser.add_argument(
        "--scaffold",
        action="store_true",
        help="Create project directory structure if it doesn't exist",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate and generate content without writing files",
    )
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    result = process_rfi(
        args.input_excel,
        args.client,
        args.project,
        scaffold=args.scaffold,
        dry_run=args.dry_run,
    )

    # Print summary
    errors = sum(1 for v in result["validation"] if v["severity"] == "ERROR")
    warnings = sum(1 for v in result["validation"] if v["severity"] == "WARNING")

    print(f"\nRFI Processing Complete")
    print(f"  Completeness: {result['completeness_score']:.0f}%")
    print(f"  Validation: {errors} errors, {warnings} warnings")
    print(f"  Files generated: {len(result['files'])}")

    if not args.dry_run:
        for path_str in result["files"]:
            print(f"    -> {path_str}")

    if errors > 0:
        print(f"\n  WARNING: {errors} validation errors found. Review rfi-followup.md")


if __name__ == "__main__":
    main()
